AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace BethanyPieShop.Controllers
{
    public class ContactController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }
    }
}

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Controllers/HomeController.cs
using BethanyPieShop.Infrastructure;
using BethanyPieShop.Model;
using Microsoft.AspNetCore.Mvc;

namespace BethanyPieShop.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPieRepository _pieRepository;

        public HomeController(IPieRepository pieRepository)
        {
            _pieRepository = pieRepository;
        }

        public ViewResult Index()
        {
            var homeViewModel = new HomeViewModel
            {
                PiesOfTheWeek = _pieRepository.PiesOfTheWeek
            };

            return View(homeViewModel);
        }
    }

}

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Controllers/OrderController.cs
using BethanyPieShop.Infrastructure;
using BethanyPieShop.Model;
using Microsoft.AspNetCore.Mvc;

namespace BethanyPieShop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderRepository _orderRepository;
        private readonly ShoppingCart _shoppingCart;

        public OrderController(IOrderRepository orderRepository, 
                               ShoppingCart shoppingCart)
        {
            _orderRepository = orderRepository;
            _shoppingCart = shoppingCart;
        }
        //[Authorize]
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
       // [Authorize]
        public IActionResult Checkout(Order order)
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            if (_shoppingCart.ShoppingCartItems.Count == 0)
            {
                ModelState.AddModelError("", "Your cart is empty, add some pies first");
            }

            if (ModelState.IsValid)
            {
                _orderRepository.CreateOrder(order);
                _shoppingCart.ClearCart();

                return RedirectToAction("CheckoutComplete");
            }

            return View(order);
        }

        public IActionResult CheckoutComplete()
        {
            ViewBag.CheckoutCompleteMessage = HttpContext.User.Identity.Name +
                                      ", thanks for your order. You'll soon enjoy our delicious pies!";
            return View();
        }
    }

}

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Controllers/PieController.cs
using System.Collections.Generic;
using System.Linq;
using BethanyPieShop.Infrastructure;
using BethanyPieShop.Model;
using Microsoft.AspNetCore.Mvc;

namespace BethanyPieShop.Controllers
{
    public class PieController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PieController(IPieRepository pieRepository, ICategoryRepository categoryRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }

        public ViewResult List(string category)
        {
            IEnumerable<Pie> pies;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                pies = _pieRepository.Pies.OrderBy(p => p.PieId);
                currentCategory = "All pies";
            }
            //else if (category == "All")
            //{
            //    pies = _pieRepository.Pies.OrderBy(p => p.PieId);
            //}
            else
            {
                pies = _pieRepository.Pies.Where(p => p.Category.CategoryName == category)
                   .OrderBy(p => p.PieId);
                currentCategory = _categoryRepository.Categories.FirstOrDefault(c => c.CategoryName == category).CategoryName;
            }

            return View(new PieListViewModel
            {
                Pies = pies,
                CurrentCategory = currentCategory
            });
        }

        [Route("[controller]/Details/{id}")]
        public IActionResult Details(int id)
        {
            var pie = _pieRepository.GetPieById(id);
            if (pie == null)
                return NotFound();

            return View(pie);
        }
    }
}

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Controllers/ShoppingCartController.cs
using System.Linq;
using BethanyPieShop.Infrastructure;
using BethanyPieShop.Model;
using Microsoft.AspNetCore.Mvc;

namespace BethanyPieShop.Controllers
{
    public class ShoppingCartController:Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IPieRepository pieRepository, ShoppingCart shoppingCart)
        {
            _pieRepository = pieRepository;
            _shoppingCart = shoppingCart;
        }


        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int pieId)
        {
            var selectedPie = _pieRepository.Pies.FirstOrDefault(p => p.PieId == pieId);

            if (selectedPie != null)
            {
                _shoppingCart.AddToCart(selectedPie, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int pieId)
        {
            var selectedPie = _pieRepository.Pies.FirstOrDefault(p => p.PieId == pieId);

            if (selectedPie != null)
            {
                _shoppingCart.RemoveFromCart(selectedPie);
            }
            return RedirectToAction("Index");
        }
    }

}

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Views/Contact/Index.cshtml
<h2>Contact Bethany's Pie Shop</h2>
<p>If you have any questinos, please don't hesitate to get in touch. Click below to send us an email.</p>
@*<a href="mailto:info@bethanyspieshop.com"></a>*@

<italic>    
    <email address="info@@bethanyspieshop.com"
           content="Contact us">
    </email>
</italic>

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Views/Home/Index.cshtml
@model HomeViewModel


@await Html.PartialAsync("Carousel")

<h2>Pies of the week</h2>
<h4>Our weekly selection - just for you!</h4>

<div class="row">

    @foreach (var pie in Model.PiesOfTheWeek)
    {
        @Html.Partial("PieOfTheWeekSummary", pie)
    }

</div>




@*<div>

        Lemon drops oat cake sesame snaps lemon drops pudding chocolate chocolate pie cheesecake. Chocolate cake halvah carrot cake. Jelly beans jelly-o dragée ice cream wafer. Topping cotton candy icing halvah cupcake jelly chocolate cake. Chocolate ice cream dessert tart biscuit dessert. Tart sweet pudding. Chocolate bar biscuit chocolate tootsie roll pudding chocolate cake. Fruitcake dessert croissant toffee. Topping pie jelly chocolate bar biscuit liquorice macaroon sesame snaps. Jujubes sesame snaps carrot cake candy gummi bears bonbon soufflé. Chocolate pie candy toffee cheesecake. Marzipan toffee bonbon. Muffin oat cake soufflé jujubes liquorice pudding wafer caramels powder. Cake muffin cookie wafer liquorice tart cookie jelly-o.
        Jujubes cake cotton candy croissant donut candy canes. Tootsie roll halvah ice cream dessert sugar plum oat cake lollipop jelly toffee. Cake chocolate danish pie lemon drops cupcake danish. Bear claw ice cream chocolate cake muffin sesame snaps. Gummi bears gummies tootsie roll lollipop liquorice macaroon jelly-o lemon drops. Jelly carrot cake cheesecake pie pie gummies tiramisu. Sugar plum wafer croissant pie pastry lollipop tiramisu gingerbread chocolate cake. Gingerbread biscuit jelly-o chocolate cake pie cake. Wafer brownie pie pudding jelly-o pastry. Lollipop muffin cotton candy fruitcake halvah jujubes brownie topping. Jelly gummi bears brownie chocolate donut candy oat cake. Jelly toffee chupa chups tootsie roll gingerbread sweet jelly. Cookie bonbon candy.

    </div>*@

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Views/Order/Checkout.cshtml
@model Order
@{
    ViewBag.Title = "title";
}

<form asp-action="Checkout" method="post" asp-antiforgery="true"
      class="form-horizontal" role="form">
    <h4>You're just one step away from your delicious pies.</h4>

    <div asp-validation-summary="All" class="text-danger">
    </div>

    <div class="form-group">
        <label asp-for="LastName" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="FirstName" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="FirstName"
                   class="form-control" />
            <span asp-validation-for="FirstName"
                  class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="AddressLine1"
               class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="AddressLine1"
                   class="form-control" />
            <span asp-validation-for="AddressLine1"
                  class="text-danger">
            </span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="AddressLine2"
               class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="AddressLine2"
                   class="form-control" />
            <span asp-validation-for="AddressLine2"
                  class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="ZipCode" 
               class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="ZipCode" 
                   class="form-control" />
            <span asp-validation-for="ZipCode" 
                  class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="City" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="City" 
                   class="form-control" />
            <span asp-validation-for="City" 
                  class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="State" 
               class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="State" 
                   class="form-control" />
            <span asp-validation-for="State" 
                  class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Country" 
               class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Country" 
                   class="form-control" />
            <span asp-validation-for="Country" 
                  class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="PhoneNumber" 
               class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="PhoneNumber" 
                   class="form-control" />
            <span asp-validation-for="PhoneNumber" 
                  class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Complete order" />
        </div>
    </div>

</form>

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Views/Order/CheckoutComplete.cshtml
<h1>@ViewBag.CheckoutCompleteMessage </h1>

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Views/Pie/Details.cshtml
@model Pie

@*<h2>@Model.Name</h2>

    <p><span>@Model.ShortDescription</span></p>
    <p><span>@Model.LongDescription</span></p>
    <p><span>@Model.AllergyInformation</span></p>
    <p><span>@Model.Price</span></p>
    <p>
        <img alt="@Model.Name" src="@Url.Content(@Model.ImageUrl)" />
    </p>

    <p class="button">
        <a asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
           asp-route-pieId="@Model.PieId">Add to cart</a>
    </p>*@



<div class="thumbnail">
    <img alt="@Model.Name" src="@Model.ImageUrl">
    <div class="caption-full">
        <h3 class="pull-right">@Model.Price</h3>
        <h3>
            <a href="#">@Model.Name</a>
        </h3>
        <h4>@Model.ShortDescription</h4>
        <p>@Model.LongDescription</p>
        <p class="button">
            <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
               asp-route-pieId="@Model.PieId">Add to cart</a>
        </p>
    </div>
</div>

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Views/Pie/List.cshtml
@model PieListViewModel

<h1>@Model.CurrentCategory</h1>
@foreach (var pie in Model.Pies)
{
   @Html.Partial("PieOverviewSummary",pie)
}

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Views/Shared/Carousel.cshtml
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<li class="dropdown">
    <a asp-controller="Pie"
       asp-action="Index"
       class="dropdown-toggle" data-toggle="dropdown">Pies<b class="caret"></b></a>
    <ul class="dropdown-menu">
        @foreach (var category in Model)
        {
            <li>
                <a asp-controller="Pie" asp-action="List"
                   asp-route-category="@category.CategoryName">@category.CategoryName</a>
            </li>
        }
        <li class="divider"></li>
        <li>
            <a asp-controller="Pie" asp-action="List" asp-route-Category="">View all pies</a>
        </li>
    </ul>
</li>

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Views/Shared/Components/ShoppingCartSummary/Default.cshtml
@model ShoppingCartViewModel

@if (Model.ShoppingCart.ShoppingCartItems.Count > 0)
{
    <li>
        <a asp-area="" asp-controller="ShoppingCart" asp-action="Index">
            <span class="glyphicon glyphicon-shopping-cart"></span>
            <span id="cart-status">
                @Model.ShoppingCart.ShoppingCartItems.Count
            </span>
        </a>
    </li>
}

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Views/Shared/PieOfTheWeekSummary.cshtml
@model Pie

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="">
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Pie" asp-action="Details" asp-route-id="@Model.PieId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart"
                   asp-route-pieId="@Model.PieId">Add to cart</a>
            </p>
        </div>
    </div>
</div>

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Views/Shared/PieOverviewSummary.cshtml
@model Pie
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3><a asp-controller="Pie" 
                   asp-action="Details"
                   asp-route-id="@Model.PieId">@Model.Name</a></h3>

            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" 
                   asp-controller="ShoppingCart" 
                   asp-action="AddToShoppingCart"
                   asp-route-pieId="@Model.PieId">Add to cart</a>
            </p>
        </div>

    </div>
</div>

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width" />
    <title>Bethany's Pie Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li><a asp-controller="Contact" asp-action="Index">Contact us</a></li>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
                @*@await Html.PartialAsync("_LoginPartial")*@
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    <img src="~/Images/bethanylogo.png" alt="" class="img-responsive" />
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

AspdotnetCore-Samples/BethanyPieShop/BethanyPieShop/Views/ShoppingCart/Index.cshtml
@model ShoppingCartViewModel
<h2>Your shopping cart</h2>
<h4>Here are the delicious pies in your shopping cart.</h4>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Selected amount</th>
            <th>Pie</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.ShoppingCart.ShoppingCartItems)
        {
            <tr>
                <td class="text-center">@line.Amount</td>
                <td class="text-left">@line.Pie.Name</td>
                <td class="text-right">@line.Pie.Price.ToString("c")</td>
                <td class="text-right">
                    @((line.Amount * line.Pie.Price).ToString("c"))
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">
                @Model.ShoppingCartTotal.ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" asp-controller="Order" asp-action="Checkout">Check out now!</a>
</div>